### ISSUE TITLE
GDTOT mirorring not working

### ISSUE THREAD

**Issue by tiktokra** [rahulkhatri137/mirrorbot137#11]
Please update repo, as GDTOT mirorring and leeching is not working...

**Comment by tiktokra** [comment]
Using GitHub workflow

**Comment by rahulkhatri137** [comment]
#12 
Test now

**Comment by tiktokra** [comment]
Still not working

**Comment by tiktokra** [comment]
Mirorring working now but, it doesn't return download/view link instead it shows "ERROR: Try in your broswer, mostly file not found or user limit exceeded!".
But file get mirrored in drive

**Comment by rahulkhatri137** [comment]
Should be fixed now

**Comment by tiktokra** [comment]
Working now, thanks...
