### ISSUE TITLE
It's not using database

### ISSUE THREAD

**Issue by AnshumanPM** [rahulkhatri137/mirrorbot137#16]
I have added postgress database Created with railway.app but it's not using that.

**Comment by rahulkhatri137** [comment]
Check ur database url bc working for others

**Comment by AnshumanPM** [comment]
Should I manually redeploy again?

**Comment by AnshumanPM** [comment]
![Screenshot_20220828_062745](https://user-images.githubusercontent.com/95046825/187058338-d17311a0-6b08-4035-8a05-b700c9c7253e.jpg)
Database added but it's not fetching that

**Comment by rahulkhatri137** [comment]
Check ur database then
Make sure it follows bot config format/template
