### ISSUE TITLE
Leech: OnUploadComplete

### ISSUE THREAD

**Issue by rahulkhatri137** [rahulkhatri137/mirrorbot137#2]
Bot doesn't delete the status message after finishing the leech upload to telegram!

**Comment by kamileecher** [comment]
Is the bot currently running or is it fixed well?

**Comment by rahulkhatri137** [comment]
Only issue with Leech. Status msg will stuck at 100%
If anyone can fix & PR then appreciated. I don't know when will I work

**Comment by rahulkhatri137** [comment]
Closing this as will be fixed on next update coming within 24 hrs
