### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by mohamedkaissi** [rahulkhatri137/mirrorbot137#26]
![Capture](https://user-images.githubusercontent.com/62901183/219886101-2bfb3d57-cb8d-4037-a4fe-fc88fe53d23b.PNG)

when uploading to gdrive , this thing happend , it finishes uploading the first time , then started uploading over again

**Comment by rahulkhatri137** [comment]
Works normal for me. I uploaded to drive yesterday too

**Comment by mohamedkaissi** [comment]
Yes the problem is from my side , storage quota exceeded, my teamdrive was unlimited, suddenly went limited, sorry my bad for opening the issue without checking logs.
