### ISSUE TITLE
CONFIG FILE URL

### ISSUE THREAD

**Issue by itsmo-ks** [rahulkhatri137/mirrorbot137#29]
Ability to load config.env file by providing it , using gist github.com , it'll will be easy to just edit the gist file , then just restart the bot , because now I have to edit the file then build the image again to make changes on the config

**Comment by rahulkhatri137** [comment]
You can use it already! I used gist & it's working normal

**Comment by itsmo-ks** [comment]
What's the variable name ? , cuz I've added this CONFIG_FILE_URL , and didn't work , it says , it can't retrieve config.env from the link .

**Comment by rahulkhatri137** [comment]
> What's the variable name ? , cuz I've added this CONFIG_FILE_URL , and didn't work , it says , it can't retrieve config.env from the link .

In logs it will show error but config will be loaded & bot will start. 
CONFIG_FILE_URL
