### ISSUE TITLE
BAN

### ISSUE THREAD

**Issue by kamileecher** [rahulkhatri137/mirrorbot137#8]
We couldn't deploy your app because the source code violates the Salesforce Acceptable Use and External-Facing Services Policy.

**Comment by rahulkhatri137** [comment]
I am already aware of that😞 U can either use workflow already available in repo to deploy on heroku, or deploy any other bot then connect that apl to this repo and deploy with that! But there are high chances of app being suspended so better clone the repo then deploy from there

**Comment by rahulkhatri137** [comment]
Fixed everything
