### ISSUE TITLE
Heroku deployment Status

### ISSUE THREAD

**Issue by Alucardx2** [rahulkhatri137/mirrorbot137#9]
Is this repo is still alive or dead?

**Comment by rahulkhatri137** [comment]
Instant ban from heroku🙂

**Comment by Alucardx2** [comment]
😢🤧

**Comment by rahulkhatri137** [comment]
> 😢🤧

Trying for a rebase to Anasty/Slam repo as this one is too old & lacks many features. But can't confirm yet. 
I am already working on options to bypass heroku bans. 1 heroku-bypass repo already exists. 
For next try, I am waiting for my application to get approved so I can start 🙂

**Comment by rahulkhatri137** [comment]
Everything is Fixed!

**Comment by scushbal** [comment]
> Everything is Fixed!

already bypass auto ban sir ?

**Comment by rahulkhatri137** [comment]
> > Everything is Fixed!
> 
> already bypass auto ban sir ?

Simply deploy from button in Readme!
No ban 🙂

**Comment by Alucardx2** [comment]
> Everything is Fixed!

Thanks sir ❣️
